Tt
weihongbin1/xx pull request #1
Opened 2021-07-22 07:23 UTC by weihongbin1

2021-07-29 03:42 UTC, weihongbin1 commented on xxw
> +as
asdfasfa

2021-07-29 03:42 UTC, 123qiuf commented on xxw
> +as
发发发发

2021-07-29 03:42 UTC, 123qiuf commented on .dockerignore
> +!build-bin/docker/docker-healthcheck
发发发发

2021-07-29 03:43 UTC, 123qiuf commented on .dockerignore
> +!build-bin/docker/docker-healthcheck
分分分

2021-07-29 08:17 UTC, 123qiuf commented on .github/ISSUE_TEMPLATE/bug.md
> +    * Otherwise, you can use a [gist](https://gist.github.com/) or pastebin such as [fluffy](https://fluffy.cc/)
烦烦烦烦烦烦烦烦烦烦烦烦

2021-07-29 08:36 UTC, weihongbin1 commented on lasdf/asfd/as/f/as/df/s/d/f/sawe/sad/f/awer/es/f/w/f/w/was/fw/e/w/er/w/ar/wa/sfas/f/adrf
> +asdfasdfas
asdasdfaskdjflasdfas

2021-08-24 02:56 UTC, QiuAnn requested changes
评审状态改变

2021-08-24 02:56 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +send a pull request (on a branch other than `master` or `gh-pages`).
这还可以修改？

2021-08-24 02:56 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +send a pull request (on a branch other than `master` or `gh-pages`).
fffff

2021-08-24 02:59 UTC, QiuAnn reviewed
> 评审状态改变

这是回复 之前评审的父级

2021-08-24 02:59 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +If you would like to contribute code, fork this GitHub repository and
第二次评审

2021-08-24 02:59 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +send a pull request (on a branch other than `master` or `gh-pages`).
评审状态下 回复之前的由评审转变为评论的

2021-08-24 03:00 UTC, QiuAnn commented on xxw
> +as
> asdfasfa
回复?

2021-08-24 03:00 UTC, QiuAnn commented on xxw
> +as
继续评论

2021-08-24 03:08 UTC, QiuAnn commented
这是普通不能再普通的评论了

2021-08-24 03:09 UTC, QiuAnn reviewed
> 这是普通不能再普通的评论了

回复最普通的评论还要 提交review?

2021-08-24 03:09 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +If you would like to contribute code, fork this GitHub repository and
第三次评审

2021-08-24 03:17 UTC, QiuAnn reviewed
在文件界面 只要是评审状态下 都是能提交评审内容或者是提交评审
回复普通的评论，发起普通评论，代码建议都是

2021-08-24 03:17 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +send a pull request (on a branch other than `master` or `gh-pages`).
> 这还可以修改？
回复普通评论

2021-08-24 03:17 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +send a pull request (on a branch other than `master` or `gh-pages`).
> 评审状态下 回复之前的由评审转变为评论的
ping发发ddf

2021-08-24 03:17 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +send a pull request (on a branch other than `master` or `gh-pages`).
> 评审状态下 回复之前的由评审转变为评论的

```suggestion
send a pull request (on a branch other than `master` or `gh-pages`).fffffffffff
```

2021-08-31 10:29 UTC, QiuAnn requested changes
2222

2021-09-02 10:17 UTC, QiuAnn reviewed
****

2021-09-02 10:18 UTC, QiuAnn reviewed
PPPPPPPPPPPPPPPPPPPPPPPPPPP

2021-09-06 02:55 UTC, QiuAnn approved these changes

2021-09-09 09:09 UTC, QiuAnn approved these changes

2021-09-09 09:09 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +
试试试·大大大

2021-09-13 02:17 UTC, QiuAnn commented on .gitattributes
> +
顶顶顶顶顶顶顶

2021-09-13 02:17 UTC, QiuAnn requested changes
发发发发

2021-09-13 02:17 UTC, QiuAnn commented on .gitattributes
> +
这是评审

2021-09-14 02:37 UTC, QiuAnn reviewed
大大

2021-09-14 02:37 UTC, QiuAnn commented on README.md
> +![LunarVim Demo](http://phpstorm.espend.de/badge/16988/version)
fffffffffffffffff

2021-09-14 02:37 UTC, QiuAnn commented on .github/workflows/create_release.yml
> +    tags: 'release-[0-9]+.[0-9]+.[0-9]+**'  # Ex. release-1.2.3
```suggestion
    tags: 'release-[0-9]+.[0-9]+.[0-9]+**'  # Ex. release-1.2.3
```

2021-09-14 02:38 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +All files are released with the Apache 2.0 license.
ff
```suggestion
All files are released with the Apache 2.0 license.发发发发发发发发
```

2021-09-16 08:50 UTC, QiuAnn requested changes
法发发

2021-09-16 08:50 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +
这是评审评审评审评审评审

2021-09-16 08:50 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +
发发发发发发发

2021-09-16 08:51 UTC, QiuAnn requested changes
法发发

2021-09-16 08:51 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +
这是评审评审评审评审评审这是评审评审评审评审评审这是评审评审评审评审评审

2021-09-16 08:53 UTC, QiuAnn requested changes
发发发发

2021-09-16 08:53 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +
这是评审评审评审评审评审这是评审评审评审评审评审这是评审评审评审评审评审这是评审评审评审评审评审这是评审评审评审评审评审

2021-09-16 08:56 UTC, QiuAnn requested changes
等到

2021-09-16 08:56 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +
这是评审评审评审评审评审2222

2021-09-16 08:57 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +
3333

2021-09-16 09:05 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +
顶顶顶顶顶

2021-09-16 09:05 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +
大大大大

2021-09-16 09:05 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +
大大大1

2021-09-16 09:06 UTC, QiuAnn reviewed
发发发发发发发发发

2021-09-16 09:06 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +
大大大大大大

2021-09-16 09:08 UTC, QiuAnn commented on .github/ISSUE_TEMPLATE/bug.md
> +labels: bug
这是评论

2021-09-16 09:08 UTC, QiuAnn reviewed
这是评审吖啊啊啊

2021-09-16 09:08 UTC, QiuAnn commented on .github/ISSUE_TEMPLATE/bug.md
> +labels: bug
这是评审大大大

2021-09-17 08:54 UTC, QiuAnn requested changes
ffffffffffff

2022-03-03 06:36 UTC, QiuAnn reviewed
提交

2022-03-03 06:36 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> + * in compliance with the License. You may obtain a copy of the License at
2022-评审

2022-03-03 06:36 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> + * in compliance with the License. You may obtain a copy of the License at
2022-评审-2

2022-03-03 06:38 UTC, QiuAnn reviewed
这是第二次

2022-03-03 06:38 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> + * in compliance with the License. You may obtain a copy of the License at
2022-评审-2fff15554444

2022-03-03 06:42 UTC, QiuAnn reviewed
这是+发起的评审

2022-03-03 06:42 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> + * in compliance with the License. You may obtain a copy of the License at
2022-评审--点击+ 发起的评审

2022-03-03 06:43 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> + * in compliance with the License. You may obtain a copy of the License at
这是在评论框评论

2022-03-03 06:46 UTC, QiuAnn reviewed
发发发发

2022-03-03 06:46 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> + * in compliance with the License. You may obtain a copy of the License at
这是文件页---发烦烦

2022-03-03 06:52 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> + * in compliance with the License. You may obtain a copy of the License at
44444

2022-03-03 06:57 UTC, QiuAnn reviewed
22

2022-03-03 06:57 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> + * in compliance with the License. You may obtain a copy of the License at
滴滴滴滴1

2022-03-03 06:58 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> + * in compliance with the License. You may obtain a copy of the License at
555

2022-03-03 09:10 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +# Contributing to Zipkin
2022-先评论

2022-03-03 09:10 UTC, QiuAnn reviewed
嗯嗯嗯

2022-03-03 09:10 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +# Contributing to Zipkin
2022--再评审

2022-03-03 09:11 UTC, QiuAnn commented on .github/CONTRIBUTING.md
> +# Contributing to Zipkin
再评论

2022-03-04 02:09 UTC, QiuAnn reviewed
这是评审

2022-03-04 02:09 UTC, QiuAnn commented on .gitattributes
> +*.bnd text=auto eol=lf
2022-3-4 评论

2022-03-04 02:11 UTC, QiuAnn commented on .gitattributes
> +*.bnd text=auto eol=lf
2022-3-4评论

2022-03-04 02:12 UTC, QiuAnn commented on .gitattributes
> +*.sh text=auto eol=lf
2022-3-4这是先评论

2022-03-04 02:12 UTC, QiuAnn reviewed
先评论 再评审

2022-03-04 02:12 UTC, QiuAnn commented on .gitattributes
> +*.sh text=auto eol=lf
2022-3-4这次是评审

2022-03-04 02:19 UTC, QiuAnn commented
13

2022-03-07 15:09 UTC, QiuAnn reviewed
评审

2022-03-07 15:09 UTC, QiuAnn commented on .dockerignore
> +# Scripts that run within Docker
2022-3-7 评审

2022-03-07 15:10 UTC, QiuAnn reviewed
1111

2022-03-07 15:10 UTC, QiuAnn commented on .dockerignore
> +# Scripts that run within Docker
2022-3-7-1

2022-03-07 15:13 UTC, QiuAnn commented on .dockerignore
> +!build-bin/maven/maven_build
普通普通评论

2022-03-07 15:14 UTC, QiuAnn reviewed
在普通代码评论下评审

2022-03-07 15:14 UTC, QiuAnn commented on .dockerignore
> +!build-bin/maven/maven_build
普通评论在评审

2022-08-18 08:13 UTC, closed without merging